UpdateMember/Controllers/LogInController.cs
using UpdateMember.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Security.Cryptography;
using System.IO;
using System.Text;
using System.Web.Security;
using UpdateMember.App_Code;
using System.Configuration;

namespace UpdateMember.Controllers
{
    public class LogInController : Controller
    {
        private Func_Log _Log = new Func_Log();
        private GiftsEntities _dbG = new GiftsEntities();
        private MemberCardEntities _dbLOG = new MemberCardEntities();
        private Cookie _Cookie = new Cookie();
        private string _SQL = string.Empty;
        private List<SqlParameter> _Parameter = new List<SqlParameter>();

        // GET: LogIn
        public ActionResult LogIn()
        {
            //if (User.Identity.IsAuthenticated)
            //{
            //    // Log Insert
            //    //string _UserNo = _Cookie.GetId();
            //    //string _EventLog = string.Format(@"{0} - Login - 會員Cookie有效，直接登入", _UserNo);
            //    //_Log.InsertSystemLog(_EventLog, _UserNo);                

            //    return RedirectToAction("Index", "UpdateMember");
            //}
            //else
            //{
            //    // Log Insert
            //    //string _UserNo = _Cookie.GetId();
            //    //string _EventLog = string.Format(@"{0} - Login - Cookie到期", _UserNo);
            //    //_Log.InsertSystemLog(_EventLog, _UserNo);

            //    //若為cookie到期自動登出時，轉頁前先清除cookie
            //    FormsAuthentication.SignOut();
            //}
            return View();
        }

        [HttpPost]
        public ActionResult LogIn(string userNo, string userPassword)
        {
            int MAX_LOGIN_TIME = int.Parse(ConfigurationManager.AppSettings["MAX_LOGIN_TIME"]);
            string ePassword = SHA512Encryption(userPassword);
            //Response.Cookies["userNo"].Value = userNo;
            //Response.Cookies["userPassword"].Value = userPassword;
            var result = _dbG.UserInfo_Setting.Where(us => us.AuthId == 1 || us.AuthId == 7).ToList();
            var finresult = result.Join(_dbG.UserInfo_Main, us => us.UserId, um => um.Id, (us, um) => new { uno = um.UserNo, pwd = um.Password }).ToList();
            var fin = finresult.Where(o => o.uno == userNo && o.pwd == ePassword).FirstOrDefault();
            FormsAuthenticationTicket ticket = new FormsAuthenticationTicket(1, userNo, DateTime.Now, DateTime.Now.AddMinutes(MAX_LOGIN_TIME), false, "", FormsAuthentication.FormsCookiePath);
            string enTicket = FormsAuthentication.Encrypt(ticket);

            // Set Cookie
            HttpCookie _HC = new HttpCookie(FormsAuthentication.FormsCookieName, enTicket);
            _HC.Expires = DateTime.Now.AddMinutes(MAX_LOGIN_TIME);
            Response.Cookies.Add(_HC); //將資料存入cookie

            _HC = new HttpCookie("LogOutTime", DateTimeOffset.UtcNow.AddMinutes(MAX_LOGIN_TIME).ToUnixTimeMilliseconds().ToString()); //存登入到期時間
            _HC.Expires = DateTime.Now.AddMinutes(MAX_LOGIN_TIME);
            Response.Cookies.Add(_HC);

            _HC = new HttpCookie("SystemTime", DateTimeOffset.UtcNow.AddMinutes(0).ToUnixTimeMilliseconds().ToString()); //存系統時間
            _HC.Expires = DateTime.Now.AddMinutes(MAX_LOGIN_TIME);
            Response.Cookies.Add(_HC);

            if (fin != null)
            {
                var rresult = new
                {
                    IsSuccess = true,
                };

                // Log Insert
                string _UserNo = _Cookie.GetId();
                string _EventLog = string.Format(@"{0} - 會員帳號密碼驗證成功", _UserNo);
                _Log.InsertSystemLog("Member - Login", _EventLog, _UserNo);

                return Json(rresult, JsonRequestBehavior.AllowGet);
                //return RedirectToAction("Index", "UpdateMember");
                //return View("Index", "UpdateMember");
            }
            else
            {
                var rresult = new
                {
                    IsSuccess = false,
                };
                //return Content(Newtonsoft.Json.JsonConvert.SerializeObject(rresult), "application/json");

                // Log Insert
                string _UserNo = _Cookie.GetId();
                string _EventLog = string.Format(@"{0} - 會員帳號密碼驗證失敗", _UserNo);
                _Log.InsertSystemLog("Member - Login", _EventLog, _UserNo);

                return Json(rresult, JsonRequestBehavior.AllowGet);
            }


        }

        /// <summary>
        /// 將欲加密的文字以SHA512的方式加密
        /// </summary>
        /// <param name="EncryptionText">加密文字</param>
        /// <returns></returns>
        public string SHA512Encryption(string EncryptionText)
        {
            //建立一個SHA512
            SHA512 EncryptionSHA = new SHA512CryptoServiceProvider();
            //將字串轉成byte[]
            byte[] source = Encoding.Default.GetBytes(EncryptionText);
            //進行SHA512加密
            byte[] crypo = EncryptionSHA.ComputeHash(source);

            //return Convert.ToBase64String(crypo);
            return BitConverter.ToString(crypo).Replace("-", string.Empty).ToLower();
        }


        public ActionResult LogOut()
        {
            if (User.Identity.IsAuthenticated)
            {
                // Log Insert
                string _UserNo = _Cookie.GetId();
                string _EventLog = string.Format(@"{0} - 會員登出", _UserNo);
                _Log.InsertSystemLog("Member - Login", _EventLog, _UserNo);
                FormsAuthentication.SignOut();
                Session.Abandon(); //清除Session內容
            }
            return RedirectToAction("Login", "Login");
        }
        public ActionResult CheckAuthenticated()
        {
            bool isAuth = User.Identity.IsAuthenticated;
            return Json(new { isAuthenticated = isAuth }, JsonRequestBehavior.AllowGet);
        }
    }
}

UpdateMember/Controllers/UpdateMemberController.cs
using UpdateMember.Models;
using UpdateMember.Models.FEDSMBR;
using UpdateMember.ViewModel;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Globalization;
using PagedList;
using PagedList.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using UpdateMember.App_Code;
using System.Net;
using System.Web.Script.Serialization;
using System.Text;
using System.IO;
using static UpdateMember.Models.viewHGAccreditation;
using System.Net.Http;
using System.Configuration;

namespace UpdateMember.Controllers
{
    public class UpdateMemberController : Controller
    {
        private Func_Log _Log = new Func_Log();
        // GET: FEDSMBR
        private FEDSMBREntities _dbFM = new FEDSMBREntities();
        // GET: MemberCard
        private MemberCardEntities _dbLOG = new MemberCardEntities();
        private DB_Connection _dbsql = new DB_Connection();
        private UpdateMember.App_Code.Cookie _cookie = new App_Code.Cookie();
        //private Cookie _cookie = new Cookie();
        private string _SQL = string.Empty;
        private List<SqlParameter> _Parameter = new List<SqlParameter>();
        Func_GetMemberCard _FGMC = new Func_GetMemberCard();

        //[Authorize]
        public ActionResult Index(int page = 1, int pagesize = 10)
        {
            string _UserNo = string.Empty;
            if (User.Identity.IsAuthenticated)
            {
                _UserNo = _cookie.GetId();
                ViewBag.UserNo = _UserNo;
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
            string _EventLog = string.Empty;
            //if (Request.Cookies[".ASPXAUTH"] == null)
            //{
            //    // Log Insert
            //    // _UserNo = _cookie.GetId();
            //    //_EventLog = string.Format(@"{0} - Index - Cookie不存在", _UserNo);
            //    //_Log.InsertSystemLog("Member - Index", _EventLog, _UserNo);

            //    return RedirectToAction("Login", "Login");

            //}
            string _sql = @"SELECT TOP(50) M.Id,ISNULL(M.Name,'-') as Name,ISNULL(M.Email,'-') as Email,Convert(varchar(10),M.Birthday,111)as Birthday,ISNULL(M.Gender,'-') as Gender,ISNULL(M.Cellphone,'-') as Cellphone,ISNULL(M.HgCardNo,'-') as HgCardNo,ISNULL(M.TempHgCardNo,'-') as TempHgCardNo,Convert(varchar(10),M.HgValidDate,111)as HgValidDate,ISNULL(M.RocId,'-') as RocId,Convert(varchar(10),M.RealValidDate,111)as RealValidDate,Convert(varchar(10),ME.ValidDate ,111) as EmailValidDate,Convert(varchar(10),MC.ValidDate ,111) as PhoneValidDate,M.Status
                            FROM 
                            (SELECT*
                            FROM Member) M
                            LEFT JOIN (SELECT MAX(ValidDate) AS ValidDate,MemberId FROM  MemberEmailValid WHERE ValidDate IS NOT NULL GROUP BY MemberId) ME ON M.Id = ME.MemberId
                            LEFT JOIN (SELECT MAX(ValidDate) AS ValidDate,MemberId FROM  MemberCellphoneValid WHERE ValidDate IS NOT NULL GROUP BY MemberId) MC ON M.Id = MC.MemberId";
            DataTable _dt = _dbsql.GetDataTable(_sql);
            List<_VResult._VMmember> result = new List<_VResult._VMmember>();

            //DateTimeFormatInfo _dtFormat = new System.Globalization.DateTimeFormatInfo();
            //_dtFormat.ShortDatePattern = "yyyy/MM/dd";


            //if (_dt.Rows.Count > 0)
            //{
            //    foreach (DataRow item in _dt.Rows)
            //    {
            //        //string _ValidExpire = Convert.ToDateTime(item["ValidExpire"]).ToShortDateString().ToString();
            //        //string _PhoneValidExpire = Convert.ToDateTime(item["PhoneValidExpire"]).ToShortDateString().ToString();
            //        //if(_ValidExpire == "1900/01/01")
            //        //{
            //        //    _ValidExpire = "-";
            //        //}
            //        //if (_PhoneValidExpire == "1900/01/01")
            //        //{
            //        //    _PhoneValidExpire = "-";
            //        //}

            //        result.Add(new _VResult._VMmember
            //        {
            //            ID = Convert.ToInt32(item["Id"]),
            //            Name = item["Name"].ToString(),
            //            ROCId = item["ROCId"].ToString(),
            //            Birthday = Convert.ToDateTime(item["Birthday"]).ToString("yyyy/MM/dd"),
            //            Gender = item["Gender"].ToString(),
            //            Email = item["Email"].ToString(),
            //            Phone = item["Cellphone"].ToString(),
            //            HappyGoCard = item["HappyGoCardNo"].ToString(),
            //            THappyGoCard = item["THappyGoCardNo"].ToString(),
            //            EmailValidExpire = item["ValidExpire"].ToString(),
            //            PhoneValidExpire = item["PhoneValidExpire"].ToString(),
            //            Status = Convert.ToInt32(item["Status"]),
            //            RealVerifyDate = item["RealVerifyDate"].ToString(),
            //        });

            //    }
            //}
            int pageIndex = page < 1 ? 1 : page;

            var model = new _VResult
            {
                _VParameter = new _VParameter(),
                PageIndex = pageIndex,
                Cards = result.ToPagedList(pageIndex, pagesize)
            };

            //return View(result.ToPagedList(page, pagesize));

            // Log Insert
            //_UserNo = _cookie.GetId();
            // _EventLog = string.Format(@"{0} - Index - 進入頁面", _UserNo);
            //_Log.InsertSystemLog(_EventLog, _UserNo);

            return View(model);
        }

        //搜尋
        [HttpPost]
        public ActionResult Index(int? id, string phoneNo, string userId, _VResult vResult, int page = 1, int pagesize = 10)
        {
            string _UserNo = string.Empty;
            if (User.Identity.IsAuthenticated)
            {
                _UserNo = _cookie.GetId();
                ViewBag.UserNo = _UserNo;
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
            string _EventLog = string.Empty;
            //if (Request.Cookies[".ASPXAUTH"] == null)
            //{
            //    // Log Insert
            //    //_UserNo = _cookie.GetId();
            //    //_EventLog = string.Format(@"{0} - Search - Cookie不存在", _UserNo);
            //    //_Log.InsertSystemLog(_EventLog, _UserNo);

            //    return RedirectToAction("Login", "Login");

            //}
            DataTable _dt = new DataTable();
            List<_VResult._VMmember> result = new List<_VResult._VMmember>();

            if (id != null || phoneNo != "" || userId != "")
            {
                string _partialsqlid = string.IsNullOrEmpty(Convert.ToString(id)) ? string.Empty : "WHERE Id = @Id";
                string _partialsqlphoneNo = string.IsNullOrEmpty(phoneNo) ? string.Empty : "WHERE Cellphone = @phoneNo";
                string _partialsqluserId = string.IsNullOrEmpty(userId) ? string.Empty : "WHERE  RocId = @userId";

                if (!string.IsNullOrEmpty(Convert.ToString(id)))
                {
                    _partialsqlphoneNo = string.IsNullOrEmpty(phoneNo) ? string.Empty : " AND Cellphone = @phoneNo";
                    _partialsqluserId = string.IsNullOrEmpty(userId) ? string.Empty : " AND  RocId = @userId";
                }
                else
                {
                    if (!string.IsNullOrEmpty(phoneNo))
                    {
                        _partialsqluserId = string.IsNullOrEmpty(userId) ? string.Empty : " AND  RocId = @userId";
                    }
                }

                string _sql = string.Format(@"SELECT TOP(50) M.Id,ISNULL(M.Name,'-') as Name,ISNULL(M.Email,'-') as Email,Convert(varchar(10),M.Birthday,111)as Birthday,ISNULL(M.Gender,'-') as Gender,ISNULL(M.Cellphone,'-') as Cellphone,ISNULL(M.HgCardNo,'-') as HgCardNo,ISNULL(M.TempHgCardNo,'-') as TempHgCardNo,Convert(varchar(10),M.HgValidDate,111)as HgValidDate,ISNULL(M.RocId,'-') as RocId,Convert(varchar(10),M.RealValidDate,111)as RealValidDate,Convert(varchar(10),ME.ValidDate ,111) as EmailValidDate,Convert(varchar(10),MC.ValidDate ,111) as PhoneValidDate,M.Status
                            FROM 
                            (SELECT*
                            FROM Member
                            {0} {1} {2}) M
                            LEFT JOIN (SELECT MAX(ValidDate) AS ValidDate,MemberId FROM  MemberEmailValid WHERE ValidDate IS NOT NULL GROUP BY MemberId) ME ON M.Id = ME.MemberId
                            LEFT JOIN (SELECT MAX(ValidDate) AS ValidDate,MemberId FROM  MemberCellphoneValid WHERE ValidDate IS NOT NULL GROUP BY MemberId) MC ON M.Id = MC.MemberId", _partialsqlid, _partialsqlphoneNo, _partialsqluserId);

                // Record Search Parameter
                string _SearchParameter = string.Empty;

                if (!string.IsNullOrEmpty(Convert.ToString(id)) && !string.IsNullOrEmpty(phoneNo) && !string.IsNullOrEmpty(userId))
                {
                    _SearchParameter = string.Format(@"搜尋參數：ID - {0} ; Phone - {1} ; UserId - {2}", id.ToString(), phoneNo, userId);

                    _Parameter.Add(new SqlParameter("@Id", id));
                    _Parameter.Add(new SqlParameter("@phoneNo", phoneNo));
                    _Parameter.Add(new SqlParameter("@userId", userId));
                    _dt = _dbsql.GetDataTable(_sql, _Parameter);
                }
                else
                {
                    _SearchParameter = @"搜尋參數：";

                    if (!string.IsNullOrEmpty(Convert.ToString(id)))
                    {

UpdateMember/Views/UpdateMember/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@*@model IEnumerable<WebApplication1.ViewModel._VMmember>*@
@model UpdateMember.ViewModel._VResult
@{
    Layout = null;
}
<!DOCTYPE html>
<html style="height:100%">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>遠東百貨 會員資料修改系統</title>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>

    <link rel="shortcut icon" href="https://www.feds.com.tw/favicon.ico" type="image/x-icon" />
    <link href="~/Content/tablestyle.css?v0.1" rel="stylesheet" />
    <link href="~/Content/headerstyle.css?v0.1" rel="stylesheet" />
    <link href="~/Content/PagedList.css?v0.1" rel="stylesheet" />
    @*<link href="~/Content/bootstrap.css" rel="stylesheet" />*@
    <link href="~/Content/bootstrap.min.css?v0.1" rel="stylesheet" />
    <link href="~/Content/windowAlert.css?v0.1" rel="stylesheet" />
    <link href="~/Scripts/fancybox/dist/jquery.fancybox.min.css?v0.1" rel="stylesheet" />
</head>
<body style="margin:0;padding:0;font-family:'Microsoft JhengHei'">
    <div id="all">
        @using (Html.BeginForm("Index", "UpdateMember", "Post"))
        {
            @*<form id="Card" action="/UpdateMember" method="post">*@
            <div id="fixed-header-slide">
                <div id="fixed-header-wrap">
                    <header>
                        <img style="position:relative;left:15px;height:60px;width:auto;padding:10px;display:block;float:left" src="~/Image/FEDS.png" />
                        <div style="float:right;padding:15px;text-align:center">
                            <span style="font-size:28px;padding:10px;color:#808080" id="showLogOutTime">
                                <script>
                                    //showLogOutTime null 顯示空字串
                                    document.getElementById("showLogOutTime").innerText = "自動登出時間：" + (sessionStorage.getItem("showLogOutTime") || "");
                                </script>
                            </span>
                            <a onclick="SweetConfirm()" style="text-decoration:none;color:#2c6cb2;">
                                <i style="color:#2c6cb2;" class="fa fa-user-circle fa-2x"></i>
                                <span style="padding:10px">登出</span>
                            </a>
                        </div>
                    </header>
                </div>
            </div>
            <div id="content">
                <div style="height:60px;width:85%;border-bottom:2px solid #808080;margin:0 auto;margin-top:80px">
                    <span style="font-size:28px;padding:10px;color:#808080">會員基本資料管理</span>

                </div>
                <div style="height:30%;width:80%;margin:0 auto;margin-top:30px">
                    <div>
                        <div class="form-group row" style="line-height:30px">
                            <div class="col-sm-3 col-lg-1 control-label right">ID</div><div class="col-lg-5 col-md-3"><input name="id" class="form-control" /></div>
                        </div>
                        <div class="form-group row" style="line-height:30px">
                            <div class="col-sm-3 col-lg-1 control-label right">電話</div><div class="col-lg-5 col-md-3"><input name="phoneNo" class="form-control" /></div>
                        </div>
                        <div class="form-group row" style="line-height:30px">
                            <div class="col-sm-3 col-lg-1 control-label right">身分證</div><div class="col-lg-5 col-md-3"><input name="userId" class="form-control" /></div>
                            @*<input type="submit" style="width:80px;height:30px;background-color:#2c6cb2;border-radius: 20px;border:1px;color:#ffffff" name="quire" value="查詢" />&nbsp;&nbsp;
                                <input type="reset" style="width:80px;height:30px;background-color:#2c6cb2;border-radius: 20px;border:1px;color:#ffffff" name="empty" value="清空" />*@
                        </div>
                        <div class="form-group row" style="margin:0 auto;margin-top:30px">
                            <input type="submit" style="width:80px;height:50px;background-color:#2c6cb2;border-radius: 20px;border:1px;color:#ffffff" name="quire" value="查詢" />&nbsp;&nbsp;&nbsp;&nbsp;
                            <input type="reset" style="width:80px;height:50px;background-color:#2c6cb2;border-radius: 20px;border:1px;color:#ffffff" name="empty" value="清空" />
                        </div>
                    </div>
                </div>
                <div style="width:80%;height:90%;margin:0 auto;margin-top:30px;display:block">
                    <div class="row">
                        @foreach (var item in Model.Cards)
                        {
                            <div style="height:19rem;width: 19rem;padding:5px">
                                <div class="card">
                                    <div class="card-body">
                                        <h5 class="card-title">@Html.DisplayFor(modelItem => item.Name)</h5>
                                        <h6 class="card-subtitle mb-2 text-muted">ID : @Html.DisplayFor(modelItem => item.ID)</h6>
                                        <p class="card-text">會員卡號 : @Html.DisplayFor(modelItem => item.MemberCardNo)</p>
                                        <p class="card-text">身分證 : @Html.DisplayFor(modelItem => item.ROCId)</p>
                                        @*<p class="card-text">生日 : @Html.DisplayFor(modelItem => item.Birthday)</p>*@
                                        @*<p class="card-text">性別 : @Html.DisplayFor(modelItem => item.Gender)</p>*@
                                        <p class="card-text">電話 : @Html.DisplayFor(modelItem => item.Phone)</p>
                                        <button type="button" id="ViewDetailButton" class="fancybox btn btn-outline-primary" data-fancybox data-type="iframe" data-src="@Url.Action("ViewDetail", "UpdateMember", new { Id = item.ID })">顯示更多</button>
                                        <button type="button" id="UpdateDetailButton" style="float:right" class="fancybox btn btn-outline-primary" data-fancybox data-type="iframe" data-src="@Url.Action("UpdateDetail", "UpdateMember", new { Id = item.ID })">編輯</button>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
                <div style="height:30%;width:250px;margin:0 auto">
                    <div class="row" @*style="margin:0 auto;display:block;float:left"*@>
                        @Html.PagedListPager(Model.Cards, page => Url.Action("Index", new { page }))
                        @*@Html.PagedListPager((IPagedList)Model, page => Url.Action("index", new { page }))*@
                    </div>
                </div>
            </div>


            @*</form>*@
        }
    </div>
</body>
</html>
<script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
<script src="~/Scripts/jquery-3.3.1.js"></script>
<script src="~/Scripts/bootstrap.js"></script>
<script src="~/Scripts/FancyBox.js"></script>
<script src="~/Scripts/fancybox/dist/jquery.fancybox.min.js"></script>
<script src="~/Scripts/windowAlert.js"></script>
<script src="~/Scripts/AutoLogOut.js"></script>
<script>
    @* 列表分頁 *@
            $(function () {
                $('.pagination>li>a[href]').each(function (i, item) {
                    var page = $(item).attr('href').replace('@Url.Content("~/UpdateMember?page=")','');
                    $(item).attr('href', '#').click(function () { postPage(page); });

                });
            });

            function postPage(page) {
                var targetFormId = '#Card';
                if ($(targetFormId).length > 0) {
                    $('<input>')
                        .attr({ type: 'hidden', id: 'PageIndex', name: 'PageIndex', value: page })
                        .appendTo($(targetFormId));
                    $(targetFormId).submit();
                }
            };
</script>
<script type="text/javascript">
    $(document).ready(function () {
        if (!sessionStorage.getItem("timeDifference")) {
            const temp = Date.now() - (getCookie("SystemTime"))
            sessionStorage.setItem("timeDifference", temp)
        }
        $('[data-fancybox]').fancybox({
            toolbar: false,
            smallBtn: true,
            clickSlide: 'false',
            touch: {
                vertical: true,  // 允許垂直方向拖拽
                momentum: true   // Continue movement after releasing mouse/touch when panning
            },
            iframe: {
                preload: false,
                //css: {

                //    width: "40%",
                //    height: "70%",

                //},
                slideShow:
                {
                    autoStart: false,
                    speed: 4000,
                },
                clickOutside: 'close',
            },
        });
    });
</script>
<script>
    @*$(window).on('pageshow', function (event) {
        // event.originalEvent.persisted 為 true 代表頁面是從快取中還原的
        //console.log("pageshow triggered. Persisted: " + event.originalEvent.persisted);
        // 每次進到頁面都去判斷登入狀態
        $.ajax({
            url: '@Url.Action("CheckAuthenticated", "LogIn")', // 確認FormsAuthentication是否登入
            type: 'GET',
            dataType: 'json',
            cache: false, //關閉快取避免抓到舊的登入狀態
            success: function (response) {
                // 後端回傳 { isAuthenticated: true/false }
                if (response.isAuthenticated == false) {
                    deleteCookie("LogOutTime");
                    sessionStorage.removeItem('showLogOutTime');
                    // 使用者已登出，移除編輯按鈕上的 FancyBox 屬性
                    $('#UpdateDetailButton,#ViewDetailButton')
                        .removeAttr('data-fancybox')
                        .removeAttr('data-type')
                        .removeAttr('data-src')
                        .off('click') // 移除 FancyBox 行為
                        .on('click', function (e) {
                            //e.preventDefault();
                            swal({
                                title: '提醒',
                                text: '您的登入狀態已失效，請先登入！',
                                type: 'warning',
                                confirmButtonColor: '#3085d6',
                                confirmButtonText: '確定'
                            }).then(function () {
                                setTimeout(function () { location.href = "@Url.Action("LogIn", "LogIn")"; }, 0);
                            })
                            window.location.href = '@Url.Action("Login", "LogIn")';
                        });
                }
            },
            error: function () {
                // 如 AJAX 請求失敗，可視需求採取措施
            }
        });
    });*@
    // 設定定時器，每秒更新頁面上的登入時長顯示
    setInterval(() => {
        checkLoginDuration();
        //document.getElementById("showLogOutTime").innerText = "自動登出時間：" + getLogOutTime();
    }, 1000);
    function SweetConfirm() {
        swal({
            title: '提醒',
            text: "確定要登出嗎？",
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: '確定',
            cancelButtonText: '取消'
        }).then(function () {
            $.ajax({
                type: "POST",
                url: '@Url.Action("Logout", "LogIn")',
                data: 'id = @ViewBag.UserNo',
                success: function (data) {
                    swal({
                        title: '登出',
                        text: '您已成功登出系統!!!!',
                        type: 'success',
                        confirmButtonColor: '#3085d6',
                        confirmButtonText: '確定'
                    }).then(function () {
                        deleteCookie("LogOutTime");
                        sessionStorage.removeItem('showLogOutTime');
                        sessionStorage.removeItem('timeDifference');
                        setTimeout(function () { location.href = "@Url.Action("LogIn", "LogIn")"; }, 0);
                    })
                }
            })
            return true;
        });
    }
    function checkLoginDuration() {
        const LogOutTime = getCookie("LogOutTime")
        const currentTime = Date.now()
        const timeDifference = sessionStorage.getItem("timeDifference")
        const fixTime = currentTime - timeDifference
        // 用修正後的時間去判斷
        if (fixTime > LogOutTime) {
            //console.log("end: " + currentTime + "  " + fixTime)
            deleteCookie("LogOutTime");
            sessionStorage.removeItem('showLogOutTime');
            sessionStorage.removeItem('timeDifference');
            location.href = '@Url.Action("Logout", "LogIn")';
        }
        else {
            //console.log(currentTime + "  " + fixTime)
        }
    }
</script>